version: '3.8'

services:
  grpc-server:
    build: ./grpc-service
    ports: 
      - "50051:50051"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: library
    # volumes:
    #  - .:/app
 
  rest-server:
    build: ./rest-service
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server
    environment:
      GRPC_SERVER_ADDR: grpc-server:50051

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
